### ISSUE TITLE
missing translation keys in filter bar (search.filters.filter.*)

### ISSUE THREAD

**Issue by saschaszott** [4Science/dspace-angular#37]
URL to reproduce the bug: https://dspacecris7.4science.cloud/search?configuration=project_funding&page=1&f.entityType=Project,equals

Unfold the sections _Researcher_ and _Organization_ on the left-hand side.

Two labels are not translated (marked red in the screenshot below).

![image](https://github.com/4Science/dspace-angular/assets/952735/c90fa9c8-28ec-4c55-8c94-30d700fdb84c)

**Comment by corrad82-4s** [comment]
Translations added with commit https://github.com/4Science/dspace-angular/commit/5e754b64f753888b55abc72e46896495431c26b6
